//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmsApp.rc
//
#define ID_CLEAR                        2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SMSAPP_DIALOG               102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_PROPSHT_CAPTION             104
#define IDD_PAGE_DEBUG                  105
#define IDS_SRV_SERVICEID               106
#define IDD_PROPPAGE_STATUS             107
#define IDD_PAGE_PARSER_TEST            108
#define IDS_SRV_FEEUSERTYPE             109
#define IDD_PROPPAGE_DEBUG              110
#define IDD_PARSER_SET                  111
#define IDS_SRV_FEETYPE                 112
#define IDD_PAGE_STATUS                 113
#define IDS_SRV_FEECODE                 114
#define IDS_SRV_MSGSRC                  115
#define IDS_SRV_NEWSERVICECODE          116
#define IDS_SRV_TYPE                    117
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_FACE                 134
#define IDD_DIALOG_INPUT_TWO            138
#define IDD_DIALOG_INPUT_ONE            139
#define IDD_SYSTEM_CONFIG               142
#define IDI_LINK                        143
#define IDD_DIALOG1                     144
#define IDD_DIALOG2                     145
#define IDC_CURSOR1                     146
#define IDB_BITMAP1                     148
#define IDI_ICON_PIC                    151
#define IDD_DlgViewDbgInfo              155
#define IDD_SETACKERROR                 156
#define IDD_ADDACKERROR                 157
#define IDD_FEECODE_CONFIG              165
#define IDB_BITMAP2                     167
#define IDD_ACCOUNTFLOW                 174
#define IDD_INPUTDESTADDR               176
#define IDB_BITMAP3                     178
#define IDD_CONFIGDLG                   180
#define IDD_CONFIGLOGPAGE               183
#define IDD_SETACKERRPAGE               185
#define IDD_CACHECONFIG                 188
#define IDD_OTHERCONFIG                 189
#define IDC_IFCOUNT                     1001
#define IDC_LIST1                       1002
#define IDC_LIST_DEBUG                  1003
#define IDC_LIST_ERR                    1004
#define IDC_LIST_FEECODE                1005
#define IDC_LIST_ACCOUNTFLOW            1006
#define IDC_SHAKEHANDNO                 1007
#define IDC_SHAKEHANDYES                1008
#define IDC_SPIN1                       1010
#define IDC_CLEAR_DEBUG_LIST            1011
#define IDC_SPIN2                       1012
#define IDC_TREE_IF_INFO                1013
#define IDC_BUTTON_REFRESH              1014
#define IDC_ORG_ADDR                    1016
#define IDC_DEST_ADDR                   1017
#define IDC_SM                          1018
#define IDC_RET                         1019
#define IDC_BEGIN_TEST                  1020
#define IDC_SETNOTIFYRES                1027
#define IDC_NOTIFYACK                   1029
#define IDC_INI_LIST_SUB                1034
#define IDC_INI_FILE_LIST               1035
#define IDC_ADD_INI_SUB                 1037
#define IDC_DEC_INI_SUB                 1038
#define IDC_ADD_INI_FILE                1039
#define IDC_DEC_INI_FILE                1040
#define IDC_CUR_FILE_NAME               1041
#define IDC_ACCESS_CODE                 1042
#define IDC_WHICH                       1043
#define IDC_WHICH2                      1044
#define IDC_FUN_STR                     1045
#define IDC_CONTANT_NAME_LIST           1046
#define IDC_DOMAIN_LIST                 1047
#define IDC_INI_LIST_SYS                1048
#define IDC_ADD_CONSTANT                1049
#define IDC_DEC_CONSTANT                1050
#define IDC_CONTANT_VALUE_LIST          1051
#define IDC_CHANGE_LIST                 1052
#define IDC_CHANGE_VALUE_LIST           1053
#define IDC_ADD_DOMAIN                  1054
#define IDC_DEC_DOMAIN                  1055
#define IDC_ADD_CHANGE                  1056
#define IDC_DEC_CHANGE                  1057
#define IDC_POSTION_LIST                1058
#define IDC_READ_GERN_INI               1059
#define IDC_BUTTON_SURE                 1060
#define IDC_EDIT_LEFT                   1061
#define IDC_EDIT_RIGHT                  1062
#define IDC_VALUE                       1062
#define IDC_RADIO_JIAN_QUAN             1063
#define IDC_RADIO_JIAN_QUAN2            1064
#define IDC_DATASOURCE_COUNT            1065
#define IDC_PORT_NUM                    1066
#define IDC_TIMEOUT                     1067
#define IDC_PARSER_PATH                 1068
#define IDC_STOCK                       1069
#define IDC_STOCK2                      1070
#define IDC_STOCK3                      1071
#define IDC_STOCK4                      1072
#define IDC_STOCK5                      1073
#define IDC_CURENT_CFG                  1074
#define IDC_CURENT_CFG2                 1075
#define IDC_SUB_DIR                     1076
#define IDC_CURENT_CFG3                 1077
#define IDC_INIFILE_TYPE                1078
#define IDC_LABEL_ACTIVE_USER_COUNT     1079
#define IDC_CURENT_CFG4                 1080
#define IDC_DYNAMIC_COUNT               1081
#define IDC_CURENT_CFG5                 1082
#define IDC_BTNDebug                    1083
#define IDC_LOADPREPAY                  1084
#define IDC_SENDCOUNT                   1085
#define IDC_RECVACK                     1086
#define IDC_ACKSUC                      1087
#define IDC_ACKFAIL                     1088
#define IDC_ACKABNOR                    1089
#define IDC_WAITCOUNT                   1090
#define IDC_SENDSUC                     1091
#define IDC_QUERY_USERFEETYPE           1091
#define IDC_SUBMIT                      1092
#define IDC_SENDFAIL                    1093
#define IDC_DELIVER                     1094
#define IDC_SENDING                     1095
#define IDC_FILECACHECOUNT              1096
#define IDC_REPORT                      1097
#define IDC_SUCREPORT                   1098
#define IDC_FAILREPORT                  1099
#define IDC_SENDQUECOUNT                1100
#define IDC_RECVAUTHREQACKCOUNT         1101
#define IDC_RESUBMIT                    1102
#define IDC_ACKERRRESUBMIT              1103
#define IDC_ACKOUTRESUBMIT              1104
#define IDC_RESENDFLAG                  1105
#define IDC_SENDAUTHCNFMCOUNT           1106
#define IDC_B_OpenDbgView               1107
#define IDC_B_SETACKERROR               1108
#define IDC_SENDAUTHREQCOUNT            1109
#define IDC_E_Error_Counter             1110
#define IDC_B_LoadFeeCode               1111
#define ID_B_Refresh                    1112
#define IDC_B_FILTER_CTRL               1113
#define IDC_SETNULL                     1114
#define IDC_B_FILTER_RELOAD             1115
#define IDC_ADDNEW                      1116
#define IDC_DEL                         1117
#define IDC_EDIT1                       1118
#define IDC_USERNUM                     1118
#define IDC_EDIT_LOG_LEVEL              1118
#define IDC_LOGLEVEL                    1119
#define IDC_REMOTEGWPATH                1121
#define IDC_COMBO1                      1122
#define IDC_ERRNO                       1123
#define IDC_COUNT                       1124
#define IDC_DEAL                        1125
#define IDC_STATIC_DBLED                1126
#define IDC_BUTTON_LOAD                 1127
#define IDC_BUTTON_STATUSF              1128
#define IDC_UNWELCOMELIST               1129
#define IDC_ADD                         1130
#define IDC_PHONENO                     1131
#define IDC_SRCPHONENO                  1132
#define IDC_SENDSUCREPORT               1133
#define IDC_SUCREPORTSENDS              1134
#define IDC_SENDFAILREPORT              1135
#define IDC_FAILREPORTSENDS             1136
#define IDC_SENDREPORT                  1137
#define IDC_ACCOUNTFLOW                 1138
#define IDREFRESH                       1139
#define IDC_CLEAR                       1140
#define IDC_FAILREPORTSEND              1141
#define IDC_SENDFAILACK                 1142
#define IDC_SUCREPORTSEND               1143
#define IDC_SENDSUCACK                  1144
#define IDC_RCVAUTHCNFMACKCOUNT         1145
#define IDC_STATISTICS                  1146
#define IDC_RESUBMITS                   1147
#define IDC_DESTADDR                    1148
#define IDC_CLEARTIME                   1149
#define IDC_SAVECACHE                   1150
#define IDC_CONFIG                      1151
#define IDC_REPORTLOGCHECK              1152
#define IDC_REPORTLOGACCNT              1153
#define IDC_ACKERRRESENDCHECK           1154
#define IDC_APPLY                       1155
#define IDC_SAVECONFIG                  1156
#define IDC_FILECACHEONOFF              1157
#define IDC_MAXFILECACHESMCOUNT         1158
#define IDC_WAITQUETIMEOUT              1159
#define IDC_BROWSE                      1160
#define IDC_FILTERCHECK                 1161
#define IDC_FILTERRELOAD                1162
#define IDC_SPMS_CHECK                  1164
#define IDC_FEEMONTHMSG_CHECK           1165
#define IDC_BUTTON1                     1167
#define IDC_BUTTON_HTTP                 1167
#define IDC_BUTTON_LOG_OPTION           1167
#define IDC_BUTTON2                     1168
#define IDC_BUTTON_LOADSERVICETABLE     1168
#define IDC_BUTTON_SOCKINFO             1168
#define IDD_QUERY_USERFEETYPE           3001
#define IDD_DIALOG_HTTP_STATUS          3002
#define IDD_DIALOG_LOGOPTION            3003
#define IDC_QUERYUFT                    5000
#define IDC_STATIC_STATUS               5000
#define IDC_PROPERTYGRID_RC             5001
#define IDC_STATIC_DRV                  5002
#define IDC_BUTTON_DUMP                 5003
#define IDC_BUTTON_CONSOLE              5004
#define IDC_QUERYUFT_RESULT             5005
#define IDC_BUTTON_DUMP_MEMLEAK         5005
#define IDC_BUTTON4                     5006
#define IDC_BUTTON_MARKMEM              5006
#define IDC_BUTTON_DUMP_V               5007
#define IDC_BUTTON3                     5008
#define IDC_BUTTON_LOG_RET              5008

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        3004
#define _APS_NEXT_COMMAND_VALUE         4000
#define _APS_NEXT_CONTROL_VALUE         5009
#define _APS_NEXT_SYMED_VALUE           6000
#endif
#endif
